name: Actualizar Dashboard MTTO

on:
  schedule:
    - cron: '0 * * * *' # Se ejecuta automáticamente cada hora
  workflow_dispatch:      # Botón para ejecutarlo manualmente cuando quieras

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar librerías necesarias
        run: |
          pip install office365-python-client Pillow

      - name: Ejecutar el script
        env:
          SP_USER: ${{ secrets.SP_USER }}
          SP_PASS: ${{ secrets.SP_PASS }}
        run: python main.py 

      - name: Publicar el HTML en GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
