name: Actualizar Dashboard MTTO

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:

# ESTO ES LO NUEVO: Le da permiso a GitHub Actions para guardar la página web
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar librerias necesarias
        run: |
          pip install Office365-REST-Python-Client Pillow

      - name: Ejecutar el script
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        run: python main.py 

      - name: Publicar el HTML en GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
